In [24]:
!pip install tensorflow

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow


In [25]:
import tensorflow as tf

In [26]:
import pandas as pd
import numpy as np
df =pd.read_csv('Credit.csv')

In [27]:
df 

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,unemployed,married,primary,1787,no,79.0,1,no
1,33.0,services,married,secondary,4789,yes,220.0,1,no
2,35.0,management,single,tertiary,1350,yes,185.0,1,no
3,30.0,management,married,tertiary,1476,yes,199.0,4,no
4,59.0,blue-collar,married,secondary,0,yes,226.0,1,no
...,...,...,...,...,...,...,...,...,...
4516,99.0,services,married,secondary,-333,yes,329.0,5,no
4517,57.0,self-employed,married,tertiary,-3313,yes,-153.0,1,no
4518,57.0,technician,married,secondary,295,no,151.0,11,no
4519,28.0,blue-collar,married,secondary,1137,no,129.0,4,no


In [28]:
# df.to_csv('clean_Credit.csv')
from sklearn.datasets import load_iris
x , y= load_iris(return_X_y=True)

In [29]:
x 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [30]:
input_shape = x.shape[1]
input_shape

4

In [31]:
y 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [82]:
df = pd.read_csv('cleaned_dataset.csv')
x=df.drop('approval',axis=1)
y =df['approval']

In [97]:
x 

,age,job,marital,education,balance,housing,duration,campaign
0,30.0,10,1,0,1787,0,79.0,1
1,33.0,7,1,1,4789,1,220.0,1
2,35.0,4,2,2,1350,1,185.0,1
3,30.0,4,1,2,1476,1,199.0,4
4,59.0,1,1,1,0,1,226.0,1
...,...,...,...,...,...,...,...,...
4496,99.0,7,1,1,-333,1,329.0,5
4497,57.0,6,1,2,-3313,1,-153.0,1
4498,57.0,9,1,1,295,0,151.0,11
4499,28.0,1,1,1,1137,0,129.0,4


In [100]:
input_shape = x.shape[1]

In [101]:
input_shape

8

In [102]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2)

In [113]:
model =Sequential()
model.add(Dense(units=128, activation='relu', input_shape=(input_shape,)))  ### input layer

# Dropout layer 
model.add(Dropout(0.2))

### hidden layer 
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=8, activation='relu'))



# output layer 

model.add(Dense(units=1, activation='sigmoid')) 



model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])


c:\Users\kumaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [114]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_45 (Dense)                │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_46 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_47 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_48 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_49 (Dense)                │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_50 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,161 (47.50 KB)

 Trainable params: 12,161 (47.50 KB)

 Non-trainable params: 0 (0.00 B)

In [115]:
model.fit(x_train , y_train , epochs=10)

Epoch 1/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6691 - loss: 15.7649
Epoch 2/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 1.2900
Epoch 3/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8255 - loss: 9.6099
Epoch 4/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8638 - loss: 0.7478
Epoch 5/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8664 - loss: 0.6414
Epoch 6/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8715 - loss: 0.5278
Epoch 7/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8450 - loss: 0.8306
Epoch 8/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8423 - loss: 0.9237
Epoch 9/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8564 - loss: 0.6183
Epoch 10/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8711 - loss: 17.2134


In [116]:
model.predict(  x_test)

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


array([[3.94302160e-02],
       [2.55057734e-04],
       [8.95187657e-09],
       [6.17361255e-03],
       [1.49254416e-15],
       [8.68359621e-06],
       [1.58084338e-04],
       [2.99927123e-08],
       [4.94450978e-06],
       [3.45433271e-03],
       [1.25255194e-02],
       [4.74241679e-05],
       [3.64995612e-09],
       [1.38136660e-04],
       [1.72938854e-07],
       [2.30645314e-02],
       [4.86142184e-08],
       [2.38771667e-03],
       [3.87819637e-06],
       [1.70652238e-05],
       [9.51277849e-04],
       [1.03927832e-19],
       [2.17081630e-10],
       [7.05516914e-06],
       [1.32932757e-06],
       [1.70452610e-11],
       [1.03325862e-03],
       [1.36892396e-13],
       [1.02636921e-08],
       [1.67936422e-02],
       [6.70045763e-02],
       [1.67254257e-05],
       [2.00853869e-03],
       [4.12893096e-05],
       [6.79738167e-13],
       [1.58714524e-15],
       [6.54526055e-04],
       [3.47692367e-05],
       [2.25703523e-16],
       [3.30812218e-11],


In [117]:
x

,age,job,marital,education,balance,housing,duration,campaign
0,30.0,10,1,0,1787,0,79.0,1
1,33.0,7,1,1,4789,1,220.0,1
2,35.0,4,2,2,1350,1,185.0,1
3,30.0,4,1,2,1476,1,199.0,4
4,59.0,1,1,1,0,1,226.0,1
...,...,...,...,...,...,...,...,...
4496,99.0,7,1,1,-333,1,329.0,5
4497,57.0,6,1,2,-3313,1,-153.0,1
4498,57.0,9,1,1,295,0,151.0,11
4499,28.0,1,1,1,1137,0,129.0,4


In [118]:
y 

0       0
1       0
2       0
3       0
4       0
       ..
4496    0
4497    0
4498    0
4499    0
4500    0
Name: approval, Length: 4501, dtype: int64