numpy 

In [2]:
# !pip install numpy 
# pip install numpy
# % pip install numpy


In [3]:
import numpy as np ## import is keyword ,  as is alias , np is alias
print(np.__version__)

1.26.4


In [4]:
lst =list(range(1,25))

In [6]:
type(lst)

list

In [7]:
# array and list 

# array is homogenous 
# list is heterogenous

# list convert into array 
arr =np.array(lst)

In [9]:
type(arr) 

numpy.ndarray

In [11]:
arr =np.array([1,2,4,5,6,7,7,7,77,7,8,8,9,3])
arr 

array([ 1,  2,  4,  5,  6,  7,  7,  7, 77,  7,  8,  8,  9,  3])

In [12]:
arr =np.arange(1,25)

In [13]:
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
arr =np.zeros(10)

In [15]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr =np.zeros((5,10)) ## 5 row  10 coloum 
arr 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
arr =np.linspace(1, 10, 5 )

In [22]:
arr 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
arr =np.arange(0,30)

In [ ]:
arr.reshape(10,3) # 3 coloum or 10 row 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [30]:
arr =np.random.randint(1,5,9)
arr 

array([2, 4, 2, 2, 3, 4, 1, 4, 4])

In [31]:
arr =np.random.randint(1,5,(5,2))

In [32]:
arr 

array([[2, 3],
       [1, 1],
       [4, 2],
       [3, 3],
       [2, 4]])

In [33]:
arr =np.random.random(10)

In [34]:
arr 

array([0.72574433, 0.58160527, 0.67680482, 0.68610898, 0.93573456,
       0.2543954 , 0.35781827, 0.64127231, 0.08734277, 0.03162575])

In [35]:
np.random.random((5,10))

array([[0.47351572, 0.87636435, 0.06722256, 0.30789781, 0.02071626,
        0.60585662, 0.9589592 , 0.39296559, 0.26090326, 0.05339826],
       [0.70530603, 0.84011528, 0.93654425, 0.58832759, 0.95548169,
        0.50850891, 0.54162381, 0.83925244, 0.02177954, 0.18639886],
       [0.35623303, 0.26677057, 0.84979994, 0.96166191, 0.81953501,
        0.77418681, 0.88624353, 0.92581053, 0.34758212, 0.11086435],
       [0.02760825, 0.96251484, 0.74915331, 0.31508645, 0.45125402,
        0.15735389, 0.38423379, 0.36298052, 0.51579977, 0.85374704],
       [0.71282136, 0.87146978, 0.56935508, 0.23216892, 0.24689305,
        0.03542663, 0.43150051, 0.6287215 , 0.84084613, 0.59615645]])

#### Array Attribute 

In [ ]:
arr =np.arange(60).reshape(12,5)  # 12 row and 5 coloum 
arr  

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [42]:
print("array shape:-",arr.shape )
print("array size:-",arr.size)
print("array datatype:- ",arr.dtype)
print("array ndim:- ",arr.ndim)

array shape:- (12, 5)
array size:- 60
array datatype:-  int32
array ndim:-  2


In [45]:
# 2d arrray convert into  1d
arr =arr.flatten()
print("array shape:-",arr.shape )
print("array size:-",arr.size)
print("array datatype:- ",arr.dtype)
print("array ndim:- ",arr.ndim)

array shape:- (60,)
array size:- 60
array datatype:-  int32
array ndim:-  1


In [46]:
lst =[[1,2,3],[4,5,6]]

In [48]:
arr=np.array(lst )
arr 

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr.shape 

(2, 3)

In [52]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

         Accessing elements from array 1D and 2D array
         for 1D array 
         [row start:row end : row step]

         For 2D array 
         [row start:row end:row step]



In [57]:
arr=np.arange(60)
arr[0:25:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [60]:
arr =arr.reshape(12,5)
arr 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [61]:
arr[1]

array([5, 6, 7, 8, 9])

In [62]:
arr[1,1]

6

In [63]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [64]:
arr[0:5,1:2]  # 0:5 row and 1:2 coloum 

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [65]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [67]:
arr[1,3:]

array([8, 9])

In [69]:
arr[7:8,4 ]=100

In [70]:
arr 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [71]:
## last element 
arr[11:12,4]

array([59])

In [72]:
arr[11,4]

59

In [73]:
arr[11,4:5]

array([59])

In [74]:
arr[11][-1]

59

In [75]:
arr[-1][-1]

59

In [80]:
arr[11,-1]

59

In [82]:
arr[:,4][11]

59

In [83]:
arr[:,4][-1]

59

In [108]:
#3d array 
arr =np.array(np.arange(225).reshape(5,15,3))

In [109]:
arr.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
arr.shape
# (5, 15, 3)
# 5 tables  
# 15 rows  
# 3 coloums  

(5, 15, 3)

In [89]:
print("Dimension of array :-",arr.ndim)

Dimension of array :- 3


In [93]:
arr[0][2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [94]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [95]:
arr[:,0,:1]

array([[  0],
       [ 45],
       [ 90],
       [135],
       [180]])

In [96]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [98]:
arr[2][3][1] =500

In [101]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 500, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [103]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])



In [104]:
print(arr+2)
print(arr*2)
print(arr1/arr2)
print(arr1*arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1**2)
print(arr1**3)
# arr.sort

[ 3  4  5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12 14 16 18 20]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  1   4   9  16  25  36  49  64  81 100]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[   1    8   27   64  125  216  343  512  729 1000]
